import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import ThemeRegistry from "@/providers/ThemeRegistry";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const vazirmatn = localFont({
    src: [
        { path: "./fonts/Vazirmatn-Light.ttf", weight: "300" },
        { path: "./fonts/Vazirmatn-Regular.ttf", weight: "400" },
        { path: "./fonts/Vazirmatn-Medium.ttf", weight: "500" },
        { path: "./fonts/Vazirmatn-SemiBold.ttf", weight: "600" },
        { path: "./fonts/Vazirmatn-Bold.ttf", weight: "700" },
        { path: "./fonts/Vazirmatn-ExtraBold.ttf", weight: "800" },
        { path: "./fonts/Vazirmatn-Black.ttf", weight: "900" },
    ],
    variable: "--font-vazir",
    display: "swap",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="fa" dir="rtl">
            <body className={`${vazirmatn.variable} antialiased`}>
                <ThemeRegistry>
                  {children}
                </ThemeRegistry>
            </body>
        </html>
    );
}
