import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ThemeRegistry from "@/providers/ThemeRegistry";
import { ToastContainer } from "react-toastify";

const vazirmatn = localFont({
    src: [
        { path: "../fonts/Vazirmatn-Light.ttf", weight: "300" },
        { path: "../fonts/Vazirmatn-Regular.ttf", weight: "400" },
        { path: "../fonts/Vazirmatn-Medium.ttf", weight: "500" },
        { path: "../fonts/Vazirmatn-SemiBold.ttf", weight: "600" },
        { path: "../fonts/Vazirmatn-Bold.ttf", weight: "700" },
        { path: "../fonts/Vazirmatn-ExtraBold.ttf", weight: "800" },
        { path: "../fonts/Vazirmatn-Black.ttf", weight: "900" },
    ],
    variable: "--font-vazir",
    display: "swap",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="fa" dir="rtl">
            <body className={`${vazirmatn.variable}`}>
                <ToastContainer
                    position="bottom-center"
                />
                <ThemeRegistry>{children}</ThemeRegistry>
            </body>
        </html>
    );
}
